FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}/agentenv-sciworld
RUN uv venv -p 3.8.13 \
    && uv pip install --torch-backend cpu -n -e .

ENTRYPOINT ["uv", "run", "sciworld", "--host", "0.0.0.0", "--port", "36001"]
