FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}/agentenv-webshop
RUN uv venv -p 3.8 \
&& cd ./webshop \
&& uv add "typing_extensions<4.6.0" && uv sync \
&& uv pip install --torch-backend cpu -n tqdm faiss-cpu \
&& uv pip install --torch-backend cpu -n -r requirements.txt \
&& uv pip install --torch-backend cpu -n -U "Werkzeug>=2,<3" "mkl>=2021,<2022" "typing_extensions<4.6.0" "gym==0.23.1" \
&& uv pip install --torch-backend cpu -n -U torch \
&& uv pip install --torch-backend cpu -n en-core-web-lg@https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.3.0/en_core_web_lg-3.3.0-py3-none-any.whl#sha256=6ce19d37dfe5280400f80a5954d41afca10cbc742b97bfcf4b0e452b6eb24273 \
&& cd search_engine \
&& mkdir -p resources resources_100 resources_1k resources_100k \
&& uv run convert_product_file_format.py \
&& uv run -m pyserini.index.lucene \
  --collection JsonCollection \
  --input resources_100 \
  --index indexes_100 \
  --generator DefaultLuceneDocumentGenerator \
  --threads 1 \
  --storePositions --storeDocvectors --storeRaw \
&& uv run -m pyserini.index.lucene \
  --collection JsonCollection \
  --input resources \
  --index indexes \
  --generator DefaultLuceneDocumentGenerator \
  --threads 1 \
  --storePositions --storeDocvectors --storeRaw \
&& uv run -m pyserini.index.lucene \
  --collection JsonCollection \
  --input resources_1k \
  --index indexes_1k \
  --generator DefaultLuceneDocumentGenerator \
  --threads 1 \
  --storePositions --storeDocvectors --storeRaw \
&& uv run -m pyserini.index.lucene \
  --collection JsonCollection \
  --input resources_100k \
  --index indexes_100k \
  --generator DefaultLuceneDocumentGenerator \
  --threads 1 \
  --storePositions --storeDocvectors --storeRaw \
&& cd ../.. \
&& uv pip install --torch-backend cpu -n -e .

ENTRYPOINT ["uv", "run", "webshop", "--host", "0.0.0.0", "--port", "36001"]