FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}

ENV SHOPPING="http://metis.lti.cs.cmu.edu:7770" \
    SHOPPING_ADMIN="http://metis.lti.cs.cmu.edu:7780/admin" \
    REDDIT="http://metis.lti.cs.cmu.edu:9999" \
    GITLAB="http://metis.lti.cs.cmu.edu:8023" \
    MAP="http://metis.lti.cs.cmu.edu:3000" \
    WIKIPEDIA="http://metis.lti.cs.cmu.edu:8888/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing" \
    HOMEPAGE="http://metis.lti.cs.cmu.edu:4399" \
    OPENAI_API_KEY="" \
    OPENAI_BASE_URL=""

RUN set -euxo pipefail \
    && uv venv -p 3.10.13 \
    && cd "${AGENTGYM_HOME}/agentenv-webarena/webarena" \
    && uv pip install --torch-backend cpu -n -r requirements.txt \
    && uv pip install --torch-backend cpu -n playwright \
    && uv run playwright install-deps \
    && uv run playwright install \
    && uv pip install --torch-backend cpu -n -e . \
    && uv pip install --torch-backend cpu -n gunicorn \
    && uv run scripts/generate_test_data.py \
    && mkdir -p ./.auth \
    && uv run browser_env/auto_login.py \
    && uv run agent/prompts/to_json.py \
    && cd .. \
    && uv pip install --torch-backend cpu -n -e .
    
ENTRYPOINT ["uv", "run", "webarena", "--host", "0.0.0.0", "--port", "36001"]