FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}
RUN uv venv -p 3.9.12 \
    && uv pip install --torch-backend cpu -n alfworld==0.3.3 \
    && uv pip uninstall -n opencv-python \
    && uv pip install --torch-backend cpu -n -e "${AGENTGYM_HOME}/agentenv-alfworld" \
    && export ALFWORLD_DATA=~/.cache/alfworld \
    && uv run alfworld-download

ENTRYPOINT ["uv", "run", "alfworld", "--host", "0.0.0.0", "--port", "36001"]