FROM agentgym-tool

WORKDIR ${AGENTGYM_HOME}/agentenv-tool
RUN uv pip install -n networkx
RUN cd ./Toolusage && wget https://huggingface.co/datasets/hkust-nlp/agentboard/resolve/main/data.tar.gz && tar -zxvf data.tar.gz && rm data.tar.gz

ENTRYPOINT ["uv", "run", "academia", "--host", "0.0.0.0", "--port", "36001"]
