FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}
RUN uv venv -p 3.9.12 && uv pip install --torch-backend cpu -n -e "${AGENTGYM_HOME}/agentenv-lmrlgym" \
    && uv pip install --torch-backend cpu -n -e "${AGENTGYM_HOME}/agentenv-lmrlgym/lmrlgym"

ENTRYPOINT ["uv", "run", "lmrlgym", "--host", "0.0.0.0", "--port", "36001"]