FROM agentgym-base

WORKDIR ${AGENTGYM_HOME}/agentenv-sqlgym
RUN uv venv -p 3.10 \
    && mkdir bird \
    && cd bird \
    && wget -c https://bird-bench.oss-cn-beijing.aliyuncs.com/train.zip \
    && unzip train.zip \
    && rm train.zip \
    && cd train \
    && unzip train_databases.zip \
    && rm train_databases.zip \
    && cd .. \
    && wget -c https://bird-bench.oss-cn-beijing.aliyuncs.com/dev.zip \
    && unzip dev.zip \
    && rm dev.zip \
    && cd dev_20240627 \
    && unzip dev_databases.zip \
    && rm dev_databases.zip \
    && cd ../.. \
    && mv bird ../bird \
    && uv pip install --torch-backend cpu -n -e . \
    && mv ../bird bird

ENV AGENTENV_SQLGYM_BIRD_PATH=./bird

ENTRYPOINT ["uv", "run", "sqlgym", "--host", "0.0.0.0", "--port", "36001"]
